### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by MartinAskestad** [MartinAskestad/grout-wm#32]
Add a github action to build the program when changes are pulled into master branch.

**Comment by PratikKumar125** [comment]
So basically, we need to build our rust application every time a new PR is merged, or commits are added in the master branch?

**Comment by MartinAskestad** [comment]
When a PR is opened or updated, running `cargo clippy` to make sure the code is fine and perhaps `cargo test` would be a good idea.

And then code is then pulled into master, run `cargo build` and create a zip file with the built program and in the future, perhaps upload to scoop or something.
